"""add journal_entries table

Revision ID: a56a35eb1c5b
Revises: 0e7c7a769a6a
Create Date: 2026-09-06 22:32:54.378933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a56a35eb1c5b'
down_revision: Union[str, Sequence[str], None] = '0e7c7a769a6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('zone_low', sa.Float(), nullable=False),
    sa.Column('zone_high', sa.Float(), nullable=False),
    sa.Column('zone_center', sa.Float(), nullable=False),
    sa.Column('strength_stars', sa.Integer(), nullable=False),
    sa.Column('timeframes_present', sa.JSON(), nullable=False),
    sa.Column('level_types_present', sa.JSON(), nullable=False),
    sa.Column('option_call_put', sa.String(length=8), nullable=True),
    sa.Column('option_strike', sa.Float(), nullable=True),
    sa.Column('option_expiration', sa.String(length=16), nullable=True),
    sa.Column('option_dte', sa.Integer(), nullable=True),
    sa.Column('option_mid_price', sa.Float(), nullable=True),
    sa.Column('option_otm_pct', sa.Float(), nullable=True),
    sa.Column('option_contract_symbol', sa.String(length=64), nullable=True),
    sa.Column('option_status', sa.String(length=32), nullable=False),
    sa.Column('strategy_version', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_created_at'), 'journal_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_journal_entries_symbol'), 'journal_entries', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_entries_symbol'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_created_at'), table_name='journal_entries')
    op.drop_table('journal_entries')
    # ### end Alembic commands ###
